[[annotation]]
file="onco_muts_sorted.bed.gz"
columns=[6,7,8,9,10]
names=["in_cgi", "cgi_mutation_type", "cgi_cancer_types", "cgi_abbreviations", "cgi_reported_by"]
ops=["flag", "self", "self", "self", "self"]

[[annotation]]
file="ccg_sorted.bed.gz"
columns=[4,5,6,7,8,9,10]
names=["cgi_gene", "cgi_gene_tumorigenesis", "cgi_gene_alterations", "cgi_gene_translocations", "cgi_gene_cancer_types", "cgi_gene_abbreviations", "cgi_gene_sources"]
ops=["self", "self", "self", "self", "self", "self", "self"]
